baseURL: "https://une.xzgl.site/"
title:                              阅读观影记录
paginate:                           5
theme:                              hugo-PaperMod
languageCode:                       zh-cn
defaultContentLanguage:             zh-cn # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir:     true
enableEmoji:                        true  # 允许使用Emoji表情
enableRobotsTXT:                    true
enableInlineShortcodes:             true
hasCJKLanguage:                     true  # 自动检测是否包含中文日文韩文,如果文章中使用了很多中文引号的话可以开启
buildDrafts:                        false
buildFuture:                        false
buildExpired:                       false
pygmentsUseClasses:                 true
summaryLength:                      70    # 摘要长度，默认是70
# googleAnalytics: UA-123-45

ignoreErrors: ["error-remote-getjson","error-remote-getcsv"]     # 忽略错误

minify:
    disableXML: true
    # minifyOutput: true

permalinks:
      post: "/:title/"

taxonomies:
          category: categories
          tag: tags
          series: series

outputs:
      home:
            - HTML
            - RSS
            - JSON

params: 
      defaultTheme:           light       # 默认dark/light
      disableThemeToggle:     false       # 不允许切换dark/light  
      ShowReadingTime:        true        # 显示阅读时间
      ShowShareButtons:       false       # 显示帖子分享栏
      ShowBreadCrumbs:        false       # 面包屑导航栏
      ShowPostNavLinks:       false       # 显示上一个/下一个帖子
      ShowCodeCopyButtons:    true        # 代码复制按钮
      disableSpecial1stPost:  false       # 禁用第一个帖子的非卡片风格
      disableScrollToTop:     false       # 禁用回到顶部按钮
      comments:               false       # 开启评论
      #author: ["Me", "You"]              # 作者
      ShowToc:                false       # 显示文章目录
      TocOpen:                false       # 文章目录默认打开/关闭
      ShowWordCount:          true        # 显示字数统计
      comments:               false       # 开启评论

      description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
      
      cover:                              # 封面图属性
            linkFullImages:   false       # 点击图片显示完整尺寸        
            responsiveImages: false       # HTML5 字段自动提供多种尺寸的图像(耗时)
      assets:
            favicon:                "icon/favicon.ico"
            favicon16x16:           "icon/favicon.ico"
            favicon32x32:           "icon/favicon.ico"
            apple_touch_icon:       "icon/favicon.ico"
            safari_pinned_tab:      "icon/favicon.ico"
markup:
    goldmark:
        renderer:
            unsafe: true

menu:                               # 菜单
  main:
    - identifier: books
      name:       阅读
      url:        /books/
      weight:     1

    - identifier: movies
      name:       观影
      url:        /movies/
      weight:     2

    - identifier: photos
      name:       相册
      url:        /photos/
      weight:     3

    - identifier: archives
      name:       归档
      url:        /archives/
      weight:     4

    - identifier: bbs
      name:       bbs
      url:        /bbs/
      weight:     5

    - identifier: message
      name:       留言
      url:        /message/
      weight:     6

    - identifier: about
      name:       关于
      url:        /about/
      weight:     7   
