# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "0 5,17,21 * * *"
  watch:
    types: [started]
#on:
#  push:
#    branches:
#      - main   # master 更新触发
jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.personal_token }}

    - name: Create local changes
      run: |
        rm -f \
        data/douban/doing/book.csv \
        data/douban/doing/movie.csv \
        data/douban/wish/book.csv \
        data/douban/wish/movie.csv

    - name: movie-done
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: movie
        status: done
        format: csv
        dir: ./data/douban/done

    - name: movie-doing
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: movie
        status: doing
        format: csv
        dir: ./data/douban/doing

    - name: movie-wish
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: movie
        status: mark
        format: csv
        dir: ./data/douban/wish

    - name: book-done
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: book
        status: done
        format: csv
        dir: ./data/douban/done

    - name: book-doing
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: book
        status: doing
        format: csv
        dir: ./data/douban/doing

    - name: book-wish
      uses: lizheming/doumark-action@master
      with:
        id: 203067519
        type: book
        status: mark
        format: csv
        dir: ./data/douban/wish

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './data/douban'
